providers:

  routerai:
    base_url: https://routerai.ru/api/v1
    api_key: ROUTER_KEY

  gemini:
    api_key: GEMINI_KEY


models:

  fast:
    provider: routerai
    model: qwen/qwen3-vl-30b-a3b-thinking
    default: true

  gemini_flash:
    provider: gemini
    model: gemini-3-flash-preview